import Canvas from "../components/Canvas";
import Head from "next/head";
import type { NextPage } from "next";
import Toolbar from "../components/Toolbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={`${styles.container} grid grid-rows-[3rem_1fr] min-h-screen`}>
			<Head>
				<title>Classroom Planner</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Toolbar />
			<Canvas />
		</div>
	);
};

export default Home;
